In [12]:
import numpy as np
n=int(input("Enter the number"))
arr=np.arange(1,n+1)
repeated_list = [arr for _ in range(n)]
for item in repeated_list:
    print(item)

Enter the number 9


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
